### ISSUE TITLE
Terminó el TP OSINT, ya te puedo escribir esto

### ISSUE THREAD

**Issue by GuidoDipietro** [jlsuh/pdep-mit-2020#1]
Me trae recuerdos a mi repo...

https://github.com/GuidoDipietro/PDP_UTN

Te invito a pasarte por https://lacajadeutn.blogspot.com/. Me gustaría agregar un enlace a este repositorio.

Un saludo, Guido

🏌️‍♀️⛳

**Comment by jlsuh** [comment]
@GuidoDipietro !
Por supuesto, ¿qué link deseas agregar?
Sale PR 🏌🏻 !

**Comment by jlsuh** [comment]
pd: tremendo blog. Diste ganas de crearme uno 😅

**Comment by GuidoDipietro** [comment]
Me refería a agregar el link de este repo en La Caja (con los créditos pertinentes, por supuesto!) en la sección de Paradigmas, a modo de sumarle recursos a esa materia. Si es que estás de acuerdo!

Gracias por entrar a chusmear el blog, todavía está medio verdecito y no sé cómo será su formato final... Irá mutando a medida que se me ocurran cosas.
Ví que también sos medianamente activo con Aportes en Utnianos, si tenés más materiales de materias me gustaría verlos... (incluso pensando en algún tipo de colaboración o co-autoría cájica :thinking:)

Un salu2 cordial

**Comment by jlsuh** [comment]
@GuidoDipietro !
Por supuesto, me copa la idea😄
Seguramente ya me hayas OSINTeado (?) pero de igual manera dejo al siguiente los links de los aportes a utnianxs:
- SSL:
  - [Cursada con Eduardo Zúñiga 2020](https://www.utnianos.com.ar/foro/tema-aporte-ssl-cursada-2020-eduardo-z%C3%BA%C3%B1iga)
- AM2:
  - [Cursada con Miguel Albione 2020](https://www.utnianos.com.ar/foro/tema-aporte-am-ii-parciales-cursada-miguel-albione-2020)
- Discreta:
  - [Post](https://www.utnianos.com.ar/foro/tema-la-gloria-de-discreta-finales-parciales-teor%C3%ADa-coloquios-tps-gu%C3%ADas): tiene materiales organizados. Probable y lastimosamente entre en decadencia puesto que no estoy en el nuevo aula virtual de la cátedra. No podría ver los materiales que publique y eso.
- AGA:
  - [Post](https://www.utnianos.com.ar/foro/tema-aporte-finales-final-aga-12-02-2019-y-otros-finales)
- AM1:
  - [Post](https://www.utnianos.com.ar/foro/tema-aporte-parciales-parciales-ami-carolina-cord%C3%B3n): cuando preparé el final yendo de oyente con la gloriosa Carolina Cordón.
  - He [aquí](https://www.utnianos.com.ar/foro/tema-finales-ami-2018-2019-2020) unos finales de la presencialidad + el drive.
- AyED:
  - [Post](https://www.utnianos.com.ar/foro/tema-aporte-finales-final-11-2-2019-y-otros-finales-algoritmos-y-estructuras-de-datos): hay muchos horrores de código, pero puede que sirva.
- Física I:
  - [Cursada con Rubén Vella 2020](https://www.utnianos.com.ar/foro/tema-aporte-f%C3%ADsica-1-parciales-rub%C3%A9n-vella-2020-grabaciones-explicativas): tiene sus videos que impartió de cada tema. Hay un minitutorial de cómo rotar los videos también. Espero que el profe no elimine los videos😅
- AdS:
  - [Post](https://www.utnianos.com.ar/foro/tema-aporte-ads-cursada-2020-diego-mansilla): me hiciste acordar que no había subido este material. También tengo la cursada del 2019 con Darío Piccirilli.

Avisame porfavor si algunos de estos links fallan o no son coherentes.
Saludos!

**Comment by GuidoDipietro** [comment]
Fua, son muchos recursos.
Los links andan todos bien. 👍 

Estoy pensando dónde poner esto en La Caja (o siquiera, si corresponde que esté ahí, o si fuera mejor tener Otra Caja :thinking:)
También me surge la idea de... ¿y si cada uno tuviera su propia Caja? viendo los repos de Nahuel.

No se me ocurre cómo nuclear todo esto en un lugar solo, de una forma relativamente sencilla como fue crear mi blog en Blogger.
Hacer un sistema para esto suena divertido, pero creo que recurso todas las materias si llego a implementar eso.

Por lo pronto creo que voy a seguir con el TP de SO y el de DDS, pero voy a tener esto dando vueltas en el fondo de mi cabeza un toquecito. A ver si se me ocurre algo interesante.

PD: Podemos seguir por WhatsApp. Si buscás bien, resulta que ya tenés mi número. :trollface:

**Comment by jlsuh** [comment]
@GuidoDipietro !
Efectivamente, los links son bastantes. En cuanto tengamos tiempo podríamos verlo mejor.
Porfavor no dudes en avisarme si debo aportar en futuras ocasiones. Me encantaría formar parte😄
